// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqeBafg9iWdKA0D1vbX8iPJ-hOnl6K-Q',
    appId: '1:808772305860:web:5ebe99ccf442a477da9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    authDomain: 'project-edumap-2026.firebaseapp.com',
    storageBucket: 'project-edumap-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNCoXXzAriP4DEA7cEOGITBr4un2EaO8',
    appId: '1:808772305860:android:24203d5bc089eedfda9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    storageBucket: 'project-edumap-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqqeBafg9iWdKA0D1vbX8iPJ-hOnl6K-Q',
    appId: '1:808772305860:web:9f862d33cddd5be1da9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    authDomain: 'project-edumap-2026.firebaseapp.com',
    storageBucket: 'project-edumap-2026.firebasestorage.app',
  );
}
