// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.windows: return windows;
      default: throw UnsupportedError('Platform not supported');
    }
  }

  // ATENÇÃO: Verifique se o projectId está correto no seu Console do Firebase
  // Se o erro 404 persistir, altere o sufixo de .firebasestorage.app para .appspot.com
  static const String _bucket = 'project-edumap-2026.firebasestorage.app';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqeBafg9iWdKA0D1vbX8iPJ-hOnl6K-Q',
    appId: '1:808772305860:web:5ebe99ccf442a477da9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    authDomain: 'project-edumap-2026.firebaseapp.com',
    storageBucket: _bucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNCoXXzAriP4DEA7cEOGITBr4un2EaO8',
    appId: '1:808772305860:android:24203d5bc089eedfda9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    storageBucket: _bucket,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqqeBafg9iWdKA0D1vbX8iPJ-hOnl6K-Q',
    appId: '1:808772305860:web:9f862d33cddd5be1da9a91',
    messagingSenderId: '808772305860',
    projectId: 'project-edumap-2026',
    authDomain: 'project-edumap-2026.firebaseapp.com',
    storageBucket: _bucket,
  );
}
